apiVersion: v1
kind: ConfigMap
metadata:
  name: resources-shield-cm
  namespace: resources-shield
data:
  protected-resources-shield-list.yaml: |
    protectedNamespaces:
      - kube-system
      - default
      - my-important-namespace
      - kyverno
      - flux-system
      - crossplane-system
      - castai-system
      - karpenter
      - cert-manager
      - calico
