apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resources-shield-crole
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["resources-shield-cm"]
    verbs: ["get", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resources-shield-crbind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resources-shield-crole
subjects:
  - kind: ServiceAccount
    name: resources-shield-sa
    namespace: resources-shield

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: resources-shield
  name: ns-read-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-read-rolebind
  namespace: resources-shield
subjects:
  - kind: ServiceAccount
    name: resources-shield-sa
    namespace: resources-shield
roleRef:
  kind: Role
  name: ns-read-role
  apiGroup: rbac.authorization.k8s.io
